### PR TITLE
Improvements to ILI9341 fonts and clipping

### PR DESCRIPTION
**Pull request by blackketter**
I've fixed some clipping bugs that occurred when drawing near the edge of the screen and added clipping rectangle that can be adjusted to limit drawing within that rectangle, smaller than the screen dimensions.

I've also added the ability to measure the size of characters and draw the new variable-width fonts opaquely and without flickering.  

Sorry for the messy patch, I'd be happy to clean it up as you might want.  Let me know what you think.

### CODE REVIEW

**Comment by PaulStoffregen** [comment]
Wow, that's a lot of lines changed!

**Comment by blackketter** [comment]
Sorry about that.  My editor adjusted too much white space. 

And the clipping changes are woven in pretty deeply, unfortunately. 

The font stuff is pretty separable, I think. 

Would you like me to rework it into some separate requests?

-dean

**Comment by sarfata** [comment]
Great stuff - I am a big fan of the "opaque" text rendering to avoid flickering when drawing text over text.

@PaulStoffregen would you be happier merging this in small chunks? I would be happy to take the opaque part and make a separate pull request if it is easier to review. (Assuming @blackketter is ok of course).

**Comment by PaulStoffregen** [comment]
> would you be happier merging this in small chunks?

Yes, please.

**Comment by asokolsky** [comment]
I use  ILI9341_t3 with LiberationSans font.  I was not able to update text without flickering.  Use of transparent vs non-transparent background does not help.  The fork by blackketter resolved the problem.  For me it is a must-have.
Thanks!

**Comment by asokolsky** [comment]
Also 
uint16_t measureTextWidth(const char* text);
uint16_t measureTextHeight(const char* text);
are highly desired because they allow to decide which parts of the screen need a wipe out.
Thanks

**Comment by asokolsky** [comment]
I found the following inconsistent: all API in the form xxxRect take as arguments x, y, w, h.
Except for setClipRect which takes x1, y1, x2, y2.
After spending an hour debugging I replaced all these with new APIs that take as argument
`struct RECT { int16_t left; int16_t top; int16_t right; int16_t bottom; }`

**Comment by blackketter** [comment]
Excellent point.  I'll make a change to fix setClipRect to the standard parameter form.
I think that having a separate type for a rectangle (and point and coordinate) would be awesome but a larger, separate change.

**Comment by blackketter** [comment]
I have a subclass that uses the following typedefs for various graphics types:
```
typedef uint16_t color_t;
typedef int16_t coord_t;

typedef struct point_t {
  coord_t x;
  coord_t y;
} point_t;

typedef struct rect_t {
  coord_t x;
  coord_t y;
  coord_t w;
  coord_t h;
} rect_t;
```
Which I've found very useful.  I've considered turning them in to classes, but haven't bothered yet.  I think this kind of change is probably worth discussing as part of the overall graphics API future (wrt Adafruit_GFX compatibility and support for other display chipsets.)

**Comment by asokolsky** [comment]
> this kind of change is probably worth discussing as part of the overall graphics API future

Agreed.
Speaking from API marketing perspective, I find that C-style structures introduce complexity without offering enough value to API users.  E.g. if you have an object for rectangle, why not to have a method to calculate its width and so on.  Here is what I have:  [declarations](https://github.com/asokolsky/Panner/blob/master/Display.h), [implementation](https://github.com/asokolsky/Panner/blob/master/Display.cpp).

Cheers!

**Comment by PaulStoffregen** [comment]
Does this clipping feature impact performance?

**Comment by blackketter** [comment]
I doubt it's measurable.  The existing comparisons against 0 and height/width are replaced with instance variables.

**Comment by blackketter** [comment]
@PaulStoffregen Anything I can do to help ease inclusion of this code?  I see that another implementation of some text measurement was merged (horizontal only, this also includes vertical).  I hate to see duplicate effort, plus the flicker-free opaque text rendering seems to be well received.

**Comment by KurtE** [comment]
Hi Paul and blackletter, I have been playing around with some of this code, and integrated some of it into my ili9341_t3n library.  In particular I have a version of the Opaque text, I am also thinking of integrating the clip rectangle in, maybe origin.

I have been playing around speeding up the drawFontChar code.  

Two parts: for transparent text, I changed: drawFontBits
Where it was iterating over the number of lines that the bits were used on, and called drawFastHLine, I instead simply call fillRect once, as I mentioned in the thread: https://forum.pjrc.com/threads/39113-Tft-T3-Fonts?p=122778&viewfull=1#post122778
My test screen program, took about 66ms to draw, without the changes it took about 71ms, so it gained some speed.  I have a few more things to try in this area.   

Then with opaque text,  my version is currently working sort of like drawChar in that it does it all in one pass.  That is it sets up a rectangle and then outputs the color words for each one in order...  There are some interesting questions on how to properly handle characters that are not fully contained in their bounding rectangle.  Some characters for example draw one pixel above the rectangle, some may extend a few pixels to left or to right.  My code currently generates the bounds between the two and uses that. 
Again my Test output screen in Opaque took: 77ms  and without the changes took: 113.  I have not tested yet how much speed could be picked up here from just the first changes above.  Also could also possibly speed up, if the stuff to the left and right of data output was drawn with two fill rects instead of doing possibly two additional  drawFastHLine for each row. 

For normal text output in Opaque would help as if you are doing something like lets say updating a clock output,  Example Arial Bold 40, the line spacing is something like: 61, but we are only outputting maybe 40-41 rows of actual data...  

Will continue to experiment in my library.  Current stuff is up at github.com\kurte\ili9341_t3n

**Comment by blackketter** [comment]
Interesting, Kurt.  I'm away from my Teensy until next week, so I can't compare your changes to mine.  Mine branch should work with your sample code, so if you have a moment I'd love to hear how they differ in performance and behavior.  Otherwise it'll have to wait til I get home.

**Comment by KurtE** [comment]
As I mentioned in the previous posting: Drawing my sample page with transparent text took 66ms and drawing with your library (not sure if it has been updated since I downloaded zip last week), took 71

For Transparent, mine took 77 and yours took 113. 

Right now adding your origin, clip rectangle code into my library.  Looks like we both need to update several more graphic output functions, like Gradient rects...

Also probably need to use offsets for readPixel/readRect?

**Comment by blackketter** [comment]
Awesome, thanks for clarifying.  I’ll try out your code when I get home.  And yes, the clip and offset needs to be added to gradient rects (and maybe more), happy to help with this!

**Comment by KurtE** [comment]
I am working my way through integrating the clip rectangle into my version of the code and I see some problems that I need to rework:

 

For example: the change to the start of fillRect:

The code was: 

// rudimentary clipping (drawChar w/big text requires this)
    if((x >= _width) || (y >= _height)) return;
    if(x < 0) {    w += x; x = 0;     }
    if(y < 0) {    h += y; y = 0;     }
    if((x + w - 1) >= _width)  w = _width  - x;
    if((y + h - 1) >= _height) h = _height - y;



New code: 

    x+=_originx;
    y+=_originy;

    // Rectangular clipping (drawChar w/big text requires this)
    if((x >= _displayclipx2) || (y >= _displayclipy2)) return;
    if((x + w - 1) >= _displayclipx2)  w = _displayclipx2  - x;
    if((y + h - 1) >= _displayclipy2) h = _displayclipy2 - y;
    if(x < _displayclipx1) x = _displayclipx1;
    if(y < _displayclipy1) y = _displayclipy1;

 

Now let’s just assume X and width (Y has same issues). Suppose displayclipx1=100 and displayclipx2=200 and we call with x=50, width=250, disregard origin

   if(50+250-1) >= 200 -> w=200-50 -> w=150

   if(50 < 100) -> x=100

 

So, after these checks: x=100, w=150 so we draw on the pixels 100-249, which is outside the bounds 100-200. Need to rework more like the older code, where if x < display_clip1, need to update x and width and then check that result to > right hand…

**Comment by blackketter** [comment]
Keep in mind that the _displayclipx/y/1/2 are precalulated as pixels in the display coordinates (i.e. 0,0,320,240), _clipx/y/1/2 are relative to the origin.    the code:

```
    x+=_originx;
    y+=_originy;
```
then move x and y into the display coordinates where the should be clipped correctly.  Does this work out for you?

**Comment by KurtE** [comment]
No, there is still an issue.  For example look at your drawFastHLine, now look at when x < _dispclipx1, you both update the x AND you update the width to remove the amount that was clipped off the left hand side, you then check the right hand side to see if you need to clip and then adjust the width field.

With the fillRect, you first check the right hand size and if necessary update the width, you then check the left hand side and simply update it, without updating the width to remove the amount that was clipped off.

**Comment by blackketter** [comment]
Oh, I see!  Good find.  I can't test here, but it seems that:
```
	if(x < _displayclipx1) x = _displayclipx1;
	if(y < _displayclipy1) y = _displayclipy1;
```
should be changed to:
```
	if(x < _displayclipx1) { x = _displayclipx1; w -= _displayclipx1-x; }
	if(y < _displayclipy1) { y = _displayclipy1; h -= _displayclipy1-y; }
```
This might explain a bug that had been reported earlier that I hadn't dug into yet.

**Comment by KurtE** [comment]
@blackketter (@PaulStoffregen ) - As I have received a couple emails about changes during the last week or two, was wondering if this Pull Request is still active?  

Also if you are finding any issues, it would be great if you could see if those issues still exist in my version of the library ili9491_t3n.  A few notes:

a) The previous github notification about changes, I think had comments/code for ILI9488?  I know they are similar, and a few of us have our own version ili9488_t3, with same support as ili9483_t3n, 
master one is up at @mjs513, my fork is I believe in sync as well.

b) Recently @mjs513 and myself added back in support for GFX fonts, back into our versions of the libraries (ili9341_t3n, ili9488_t3, @mjs513's version of st7735/89 which is in PR).  This includes support for both transparent and opaque outputs.  

We did b) as the update that @mjs513 did for st7735_t3(89), made it again more compatible with ili9341_t3(n) library, which removed it's use of GFX.  As we were concerned about breaking compatibility for any sketches that were using GFX fonts we added the support back in and then ported those changes to the other libraries. 

So again not sure of the state of this Pull Request, which originated 4 years ago.

Kurt

**Comment by blackketter** [comment]
Hi, sorry about the spam, I had forgotten about this pull request.  

As you noticed, I had recently added support for ILI9488 to my fork, it seems that they are close enough that there's no reason for two separate libraries, except for backward compatibility (I'm using both displays for different hardware versions of the same project.)  

I'll close this pull request.  I'm still a little confused about the different forks of this library, I'd love to see a single version that could be easily maintained across different hardware (various displays, teensy versions).  Not sure how feasible that is.

**Pull request closed without merging**
